version: '3.9'

networks:
  public:
    name: ${PUBLIC_NETWORK:-public}

services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    networks:
      - public
    volumes:
      - $PWD:/app
    environment:
      - VIRTUAL_HOST=springboot.develop
      - VIRTUAL_PORT=8080